### ISSUE TITLE
Add a setting NO_UPLOAD

### ISSUE THREAD

**Issue by obirider** [otherguy/docker-dropbox#10]
It would be great to have a setting (docker environment variable) `NO_UPLOAD`. If the setting is set to true, then the client will never upload changed files. This way I could restrict other applications from changing / manipulating files in the cloud.

**Comment by otherguy** [comment]
Thanks for your suggestion @obirider!

How would that work? Is that something the default Dropbox client already supports?

This project is merely a "wrapper" (so to speak) to make the official Dropbox client available in a Docker container. It does not modify the Dropbox client in any significant way.

**Comment by obirider** [comment]
Oh I see, I think the offical Dropbox client doesn't have such a feature. Other file syncronization tools/clouds (ex. Onedrive, [https://github.com/abraunegg/onedrive](https://github.com/abraunegg/onedrive)) have similar possibilities where a setting `--download-only` indicates, that the local folder will be updated from the remote folder but not vice versa.

**Comment by otherguy** [comment]
I see. I'm sorry about that but since the Dropbox client is being installed as a binary directly from Dropbox itself, it cannot be modified in such a way.

You do have access to the Dropbox command line switches though. Maybe the `exclude` feature is enough?

https://www.mankier.com/1/dropbox

**Comment by obirider** [comment]
According to documentation `exclude` is to stop sycronization in both directions not only to stop the upload.

Thank you anyway

**Comment by otherguy** [comment]
Yeah, I wasn't exactly sure what you were trying to achieve.

I don't think what you are looking for is possible, even with 3rd party clients like [Maestral](https://github.com/SamSchott/maestral).
