### ISSUE TITLE
Sync selected Dropbox folder

### ISSUE THREAD

**Issue by bigfeetneedbigboots** [otherguy/docker-dropbox#14]
Hi and thank you for your work on this.

I'd like to limit the syncing of Dropbox down to a selected folder (including its subfolders and files).

I've tried extending the /opt/dropbox/Dropbox mapping to /opt/dropbox/Dropbox/folder1/folder2/folder3 but that hasn't worked and it is still syncing everything.

Are you able to show me how to achieve this or accept this as a feature request?

Thanks very much.

Jason

**Comment by otherguy** [comment]
Hi @bigfeetneedbigboots! I'm happy to help but I need some additional information.

What exactly are you trying to achieve that you can't achieve by syncing the whole /opt/dropbox/Dropbox folder? How should the folder structure on another device (or dropbox.com) look like?

**Comment by bigfeetneedbigboots** [comment]
Thanks for quick reply @otherguy. 

I am trying to use Dropbox to backup selected files/directories on my server. My plan was to have your docker container running and mapped to a specific local directory. I would use a rsync command to copy files/directories into that local directory as required. Your container would then sync these with Dropbox and I would always have the latest config and other important stuff in Dropbox to use as needed.

**Comment by otherguy** [comment]
Sure thing! Alright, this is something you can do already, to an extent. Take a look at the [Manage Dropbox Settings](https://github.com/otherguy/docker-dropbox#manage-dropbox-settings) section in the README.

So you would start the dropbox container and, on your server, point it to (for example) `/srv/dropbox`) by adding `-v "/srv/dropbox:/opt/dropbox/Dropbox"`.

This would sync your whole dropbox content to `/srv/dropbox`. Now to exclude folders you have on Dropbox already and you don't want synced to your server, run this command on the server:

```
$ docker exec -it <dropbox-container-name> gosu dropbox dropbox exclude add /opt/dropbox/Dropbox/<folder-to-exclude>
```

There is also this command to list current exclusions:

```
$ docker exec -it <dropbox-container-name> gosu dropbox dropbox exclude list
```

You can exclude multiple folders by running the exclude command multiple times. You can even exclude everything but a specific folder:

```
$ docker exec -it <dropbox-container-name> gosu dropbox dropbox exclude add /opt/dropbox/Dropbox/*
$ docker exec -it <dropbox-container-name> gosu dropbox dropbox exclude remove /opt/dropbox/Dropbox/<folder-to-keep>
```

Now, to exclude *local* files that you place in the `/srv/dropbox` folder from being synced up to Dropbox, you can apply the `com.dropbox.ignored` attribute to the file. This is easily done by running:

```
$ attr -s com.dropbox.ignored -V 1 /srv/dropbox/<file-to-not-sync>
```

You can find [more information about this feature here](https://help.dropbox.com/files-folders/restore-delete/ignored-files).

**Comment by bigfeetneedbigboots** [comment]
Wow, thanks for all the info.

What I now realise I have neglected to tell you is that I am using docker-compose to manage and start the dropbox container. I put the settings in my docker-compose.yml file like this:

```
# Dropbox
  dropbox:
    image: otherguy/dropbox
    container_name: dropbox
    environment:
      - TZ=${TZ}
      - DROPBOX_UID=${PUID}
      - DROPBOX_GID=${PGID}
    volumes:
      - ${USERDIR}/docker/dropbox/config:/opt/dropbox/.dropbox
      - ${USERDIR}/dropbox:/opt/dropbox/Dropbox
    restart: unless-stopped
```

Because this manages the whole process, I am not sure how to do the inclusions and exclusions you discuss in your reply above. Maybe I have gone into the realm of "unsupported" but I hope not.

**Comment by otherguy** [comment]
This would not change anything, I use compose as well.

The `<dropbox-container-name>` in my explanation is going to be `dropbox` for you (because of line 2 in your `docker-compose.yml`). So the commands will become:

```
$ docker exec -it dropbox gosu dropbox dropbox exclude [add/remove/list]
```

Note that the exclusion settings are saved in the dropbox settings path, which maps to `${USERDIR}/docker/dropbox/config` for you. Therefore, these settings are persisted not only between restarts, but even when you tear down your compose stack (`docker-compose down && docker-compose rm`).

**Comment by bigfeetneedbigboots** [comment]
I get it now. Unfortunately no joy yet.

I started the container back up, ran the following command:

`docker exec -it dropbox gosu dropbox dropbox exclude add /opt/dropbox/Dropbox/*`

then looked at the logs again. Unfortunately it is still downloading my entire dropbox contents to the local server. I also tried the above command again but without the "/*" on the end but that didn't help either.

The first command appeared to work OK because the command and response was:

`$ docker exec -it dropbox gosu dropbox dropbox exclude add /opt/dropbox/Dropbox/*
Excluded: 
*`

Any ideas what might be causing it to continue to fail?

**Comment by otherguy** [comment]
What is the output of:

```
docker exec -it dropbox gosu dropbox dropbox exclude list
```

**Comment by bigfeetneedbigboots** [comment]
Seems the earlier command didn't take (despite indicating it did).

Output:
`$ docker exec -it dropbox gosu dropbox dropbox exclude list`
`No directories are being ignored.`

**Comment by bigfeetneedbigboots** [comment]
Update:

I ran the following commands (in order):
`$ docker exec -it dropbox gosu dropbox dropbox exclude add /opt/dropbox/Dropbox/Apps`
`docker exec -it dropbox gosu dropbox dropbox exclude add /opt/dropbox/Dropbox/Private`
`docker exec -it dropbox gosu dropbox dropbox exclude add /opt/dropbox/Dropbox/Public`
`docker exec -it dropbox gosu dropbox dropbox exclude add /opt/dropbox/Dropbox/Photos`
`docker exec -it dropbox gosu dropbox dropbox exclude list`

The output of the last command was:
`$ docker exec -it dropbox gosu dropbox dropbox exclude list
Excluded: 
Apps
Photos
Private
Public`

So seems that individual folder adds to the exclusion list works but not the wildcard add.

**Comment by otherguy** [comment]
I see. From this issue I assume you use `bash`. The wildcard `*` is expanded before being handed off to Docker.

This should work:

```
$ docker exec -it dropbox gosu dropbox dropbox exclude add '/opt/dropbox/Dropbox/*'
```

**Comment by bigfeetneedbigboots** [comment]
Unfortunately that didn't work. The files and directories are still there in my local dropbox directory (except those which I have added to the exclusion list in my last reply).

What is odd is that the response I get when entering both the original command and the updated one in your last reply is that it has been successful i.e.
`$ docker exec -it dropbox gosu dropbox dropbox exclude add '/opt/dropbox/Dropbox/*'`
`Excluded: `
`*`

However when I run the list command the wildcard isn't listed as one of the exclusions, only the individual directories I did before.

**Comment by otherguy** [comment]
Well unfortunately Dropbox cannot exclude wildcard. But I was hoping that the shell inside the container would expand the wildcard.

Please get a shell into the container and try it from there:

```
$ docker exec -it dropbox sh
# cd /opt/dropbox/Dropbox
# gosu dropbox dropbox exclude add *
```

**Comment by bigfeetneedbigboots** [comment]
I did that and it worked. Everything was excluded and removed from the server. Nice job!

I then created a folder on the server and it was sync'ed to Dropbox and then down onto my PC. Perfect.

Just for giggles, I created a folder on my PC and unfortunately it was sync'ed to Dropbox and then onto the server. 

So it would seem that the wildcard exclusion is only a point-in-time rule, not an ongoing affair. Yes?

**Comment by otherguy** [comment]
That's correct. You're relying on your local shell to expand the wildcard (you can try it by typing `*` in your local `bash`and then pressing the _Tab_ key).

Unfortunately, there is no way to exclude future folders with the native tools provided by Dropbox.

It might be possible to set something up using [`inotify`](https://man7.org/linux/man-pages/man7/inotify.7.html) and execute the above command based on that, but that is beyond the scope of this container.

**Comment by otherguy** [comment]
I'm closing this ticket for now. I hope I could help you! Feel free to continue asking questions here.

**Comment by bigfeetneedbigboots** [comment]
Thanks for your help @otherguy

**Comment by tobz-nz** [comment]
Is there a way to exclude folders from a ssh session to the container? 
I have it hosted on a service where I do not have host level access.

I've tried running `dropboxd exclude list folder-1` and this is the output I get - and it doesn't seem to update the exclude list.

```
/container/dropbox/bin/dropboxd exclude exclude list folder-1
dropbox: load fq extension '/container/dropbox/bin/dropbox-lnx.x86_64-202.4.5551/cryptography.hazmat.bindings._openssl.abi3.so'
dropbox: load fq extension '/container/dropbox/bin/dropbox-lnx.x86_64-202.4.5551/cryptography.hazmat.bindings._padding.abi3.so'
dropbox: load fq extension '/container/dropbox/bin/dropbox-lnx.x86_64-202.4.5551/apex._apex.abi3.so'
dropbox: load fq extension '/container/dropbox/bin/dropbox-lnx.x86_64-202.4.5551/psutil._psutil_linux.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/container/dropbox/bin/dropbox-lnx.x86_64-202.4.5551/psutil._psutil_posix.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/container/dropbox/bin/dropbox-lnx.x86_64-202.4.5551/google._upb._message.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/container/dropbox/bin/dropbox-lnx.x86_64-202.4.5551/tornado.speedups.cpython-38-x86_64-linux-gnu.so'
dropbox: load fq extension '/container/dropbox/bin/dropbox-lnx.x86_64-202.4.5551/wrapt._wrappers.cpython-38-x86_64-linux-gnu.so'
```
