### ISSUE TITLE
/tmp access issue in container ?

### ISSUE THREAD

**Issue by fiveangle** [otherguy/docker-dropbox#15]
Thanks for putting this image together !

I noticed an oddity in the logs regarding /tmp:

```
...
Syncing 48,351 files • 5 mins,
Indexing 273 files (27 secs),
Uploading 18,235 files (0.0 KB/sec, 5 mins),
Downloading 29,843 files (0.0 KB/sec, 2 mins),
/usr/bin/find: ‘/tmp’: No such file or directory,
Syncing 48,351 files • 5 mins,
Indexing 273 files (27 secs),
Uploading 18,235 files (0.0 KB/sec, 5 mins),
Downloading 29,843 files (0.0 KB/sec, 2 mins),
/usr/bin/find: ‘/tmp’: No such file or directory,
Syncing 48,351 files • 5 mins,
Indexing 273 files (27 secs),
Uploading 18,235 files (0.0 KB/sec, 5 mins),
Downloading 29,843 files (0.0 KB/sec, 2 mins),
/usr/bin/find: ‘/tmp’: No such file or directory,
...

```

It's pretty much constant.  From within the context of the container it does appear there's no /tmp mounted:

```
root@1f10bd127f5e:/opt/dropbox/Dropbox# cd /tmp
bash: cd: /tmp: No such file or directory
root@1f10bd127f5e:/opt/dropbox/Dropbox# cd /
root@1f10bd127f5e:/# ls -l
total 76
drwxr-xr-x   1 root root 4096 Jan  8 01:40 bin
drwxr-xr-x   2 root root 4096 Nov 22 04:37 boot
drwxr-xr-x   5 root root  340 Jan 10 20:50 dev
-rwxrwxr-x   1 root root 3529 Jan  8 01:39 docker-entrypoint.sh
drwxr-xr-x   1 root root 4096 Jan 10 20:50 etc
drwxr-xr-x   2 root root 4096 Nov 22 04:37 home
drwxr-xr-x   1 root root 4096 Jan  8 01:40 lib
drwxr-xr-x   2 root root 4096 Dec  9 15:22 lib64
drwxr-xr-x   2 root root 4096 Dec  9 15:22 media
drwxr-xr-x   2 root root 4096 Dec  9 15:22 mnt
drwxr-xr-x   1 root root 4096 Jan  8 01:40 opt
dr-xr-xr-x 232 root root    0 Jan 10 20:50 proc
drwx------   2 root root 4096 Dec  9 15:22 root
drwxr-xr-x   3 root root 4096 Dec  9 15:22 run
drwxr-xr-x   1 root root 4096 Jan  8 01:40 sbin
drwxr-xr-x   2 root root 4096 Dec  9 15:22 srv
dr-xr-xr-x  13 root root    0 Jan 10 20:50 sys
drwxr-xr-x   1 root root 4096 Dec  9 15:22 usr
drwxr-xr-x   1 root root 4096 Dec  9 15:22 var
root@1f10bd127f5e:/
```

While it's of course available on the host:

```
root@kobets:/# ls -ld tmp
drwxrwxrwt 11 root root 4096 Jan 11 04:59 tmp

```

I'm new to docker just this weekend so I'm not sure if this is a red herring or not.

I haven't noticed any ill affects other than the log spam, but will update if I find anything more on this. Feel free to close if this is working-as-designed.

Thanks again for the effort to maintain this updated dropbox image !

-=dave

**Comment by otherguy** [comment]
Hi Dave,

thank you for your bug report. This is definitely *not* working as intended then and it seems you uncovered a different bug that I was trying to fix with that line.

Could you please download the newly released [`1.6.2`](https://github.com/otherguy/docker-dropbox/releases/tag/1.6.2) image and try to see if this is working for you?

**Comment by fiveangle** [comment]
https://github.com/otherguy/docker-dropbox/commit/d9893e09091f7c958e79ae323eefa0e19f1671f1 resolved.  Thanks for the fast response !

**Comment by otherguy** [comment]
Of course! Glad I could help you and thanks for the bug report!
