### ISSUE TITLE
Dropbox isn't syncing

### ISSUE THREAD

**Issue by ideepg** [otherguy/docker-dropbox#2]
So after the account linking there is an alert generated

> [ALERT]: So your files continue to sync, sign in to your Dropbox account and move Dropbox to a supported file system.

The files donot sync in the background, therefore I execute from the terminal

> docker exec -t -i dropbox dropbox status
Response is
> Dropbox isn't running!

Am I missing something?

**Comment by otherguy** [comment]
Hi @ideepg ! What command (full command) do you use to run the container and what OS are you running it on?

**Comment by otherguy** [comment]
Can you please try pulling the `:latest` version and report back whether it's working?

**Comment by ideepg** [comment]
Nope it's the same state. Not working. 
It says 

> 
This computer is now linked to Dropbox. Welcome AccountName
[ALERT]: So your files continue to sync, sign in to your Dropbox account and move Dropbox to a supported file system.`
docker exec -t -i dropbox dropbox status                                                                                                                            
Dropbox isn't running!

**Comment by otherguy** [comment]
@ideepg very strange. Please tell me what operating system you are using and what exact command you use to run the container.

By the way, I mentioned in the readme that the correct command is:

```
$ docker exec -it dropbox gosu dropbox dropbox status
Sync paused
```

**Comment by ideepg** [comment]
> docker run --detach --name=dropbox --restart=always \                                                                                                                                   
-v "/Users/<user>/Documents/Docker_mounts/Dropbox_settings:/opt/dropbox/.dropbox" \
-v "/Users/<user>/Documents/Docker_mounts/Dropbox:/opt/dropbox/Dropbox" \
--net="host" \
  otherguy/dropbox:latest

Then using the command 

> docker logs --follow dropbox

Then it gives the link.
I copy the link and hit the link in browser
I link the account
Then it says 

> This computer is now linked to Dropbox. Welcome <name>
[ALERT]: So your files continue to sync, sign in to your Dropbox account and move Dropbox to a supported file system.

Dropbox_settings folder is populated with lot of files 
Dropbox folder only contains the  .dropbox_cache file
Now when I hit the command

> docker exec -it dropbox gosu dropbox dropbox status

It says 

> Syncing paused

I am using MacOS Catalina 10.15.2 and I am using the Docker Desktop

**Comment by otherguy** [comment]
@ideepg are you sure you have the latest image? `docker pull otherguy/dropbox:latest`

If you do, and it's still not working, please add: `-e DROPBOX_UID=$(id -u) -e DROPBOX_GID=$(id -g)` to the run command.

**Comment by ideepg** [comment]
yeeah I have the latest image and I added the environment variables...but its the same error

**Comment by otherguy** [comment]
Can you please post the full output when you start the image?

**Comment by otherguy** [comment]
@ideepg can you please post the full output?

**Comment by ideepg** [comment]
> Starting dropboxd (87.4.138)...
error: exec failed: no such file or directory
Checking for latest Dropbox version...
Latest   : 87.4.138
Installed: 87.4.138
Dropbox is up-to-date

Patching dropbox_start.py for updated dropboxd path

Starting dropboxd (87.4.138)...
error: exec failed: no such file or directory

I am getting this in loop

**Comment by otherguy** [comment]
@ideepg please post the *full* output. This is only a part of it. Start the container without the `-d` / `--detach` flag, so you can see the full output from the beginning.

Please also add the *full* command that you use to start the container.

**Comment by ideepg** [comment]
> docker run --name=dropbox --restart=always \                                                                                                                                           ░▒▓ ✔ | at minikube ⎈ | at 20:38:00  
-v "/Users/user/Docker_mounts/Dropbox_settings:/opt/dropbox/.dropbox" \
-v "/Users/user/Docker_mounts/Dropbox:/opt/dropbox/Dropbox" \
--net="host" \
  otherguy/dropbox:1.3.0

DROPBOX_UID not specified, defaulting to dropbox user id (1000)
DROPBOX_GID not specified, defaulting to dropbox user group id (1000)
Checking for latest Dropbox version...
Latest   : 87.4.138
Installed: 87.4.138
Dropbox is up-to-date

Patching dropbox_start.py for updated dropboxd path

Starting dropboxd (87.4.138)...
dropbox: locating interpreter
!! dropbox: failed to create log file (Permission denied)!
dropbox: initializing
dropbox: initializing python 3.7.5
dropbox: setting program path '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/dropbox'
dropbox: setting python path '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138:/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/python-packages.zip'
dropbox: python initialized
dropbox: running dropbox
dropbox: setting args
dropbox: applying overrides
dropbox: running main script
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/cryptography.hazmat.bindings._constant_time.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/cryptography.hazmat.bindings._openssl.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/cryptography.hazmat.bindings._padding.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/psutil._psutil_linux.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/psutil._psutil_posix.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/linuxffi.pthread._linuxffi_pthread.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/cpuid.compiled._cpuid.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/apex._apex.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/tornado.speedups.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/linuxffi.resolv.compiled._linuxffi_resolv.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/librsyncffi.compiled._librsyncffi.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/linuxffi.sys.compiled._linuxffi_sys.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/posixffi.libc._posixffi_libc.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/linuxffi.gnu.compiled._linuxffi_gnu.cpython-37m-x86_64-linux-gnu.so'
>>> Dropbox started successfully
Connecting...
Connecting...
Starting...
Couldn't start Dropbox.
This is usually because of a permissions error. Storing your home folder on a network share can also cause an error.

Get more help at https://www.dropbox.com/c/help/permissions_error

Please contact Dropbox support with the following info for help:

/var/tmp/dropbox_errorkv83vi84.txt
Starting...▓▒░


The error file contains 

> bn.BUILD_KEY: Dropbox
bn.VERSION: 87.4.138
bn.DROPBOXEXT_VERSION: failed
bn.is_frozen: True
machine_id: a5a85d16-1208-265b-ec1c-6fb020b29456
pid: 37
ppid: 1
ppid exe: failed
uid: 1000
user_info: pwd.struct_passwd(pw_name='dropbox', pw_passwd='x', pw_uid=1000, pw_gid=1000, pw_gecos='Dropbox Daemon Account', pw_dir='/opt/dropbox', pw_shell='/usr/sbin/nologin')
effective_user_info: pwd.struct_passwd(pw_name='dropbox', pw_passwd='x', pw_uid=1000, pw_gid=1000, pw_gecos='Dropbox Daemon Account', pw_dir='/opt/dropbox', pw_shell='/usr/sbin/nologin')
euid: 1000
gid: 1000
egid: 1000
group_info: grp.struct_group(gr_name='dropbox', gr_passwd='x', gr_gid=1000, gr_mem=[])
effective_group_info: grp.struct_group(gr_name='dropbox', gr_passwd='x', gr_gid=1000, gr_mem=[])
LD_LIBRARY_PATH: None
cwd: '/opt/dropbox'
     real_path='/opt/dropbox'
           	mode=0o40755	uid=1000	gid=1000
     parent	mode=0o40755	uid=0	gid=0
HOME: '/opt/dropbox'
appdata: '/opt/dropbox/.dropbox/instance1'
         real_path='/opt/dropbox/.dropbox/instance1'
               	mode=0o40700	uid=1000	gid=1000
         parent	mode=0o40755	uid=1000	gid=1000
dropbox_path: '/opt/dropbox/Dropbox'
              real_path='/opt/dropbox/Dropbox'
                    	mode=0o40755	uid=1000	gid=1000
              parent	mode=0o40755	uid=1000	gid=1000
sys_executable: '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/dropbox'
                real_path='/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/dropbox'
                      	mode=0o100755	uid=1000	gid=1000
                parent	mode=0o40775	uid=1000	gid=1000
trace.__file__: '/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/python-packages.zip/dropbox/client/ui/common/boot_error.pyc'
                real_path='/opt/dropbox/bin/dropbox-lnx.x86_64-87.4.138/python-packages.zip/dropbox/client/ui/common/boot_error.pyc'
                      	not found
                parent	not found
tempdir: '/var/tmp'
         real_path='/var/tmp'
               	mode=0o41777	uid=0	gid=0
         parent	mode=0o40755	uid=0	gid=0
Traceback (most recent call last):
  File "dropbox/client/main.pyc", line 822, in wrapper
  File "dropbox/client/main.pyc", line 6846, in finish_dropbox_boot
  File "dropbox/client/main.pyc", line 6291, in _init_components_for_account
  File "dropbox/client/main.pyc", line 6245, in create_sync_engine
  File "dropbox/sync_engine_boundary/factory.pyc", line 349, in make_sync_engine
  File "dropbox/sync_engine/nucleus/classic_client/sync_engine.pyc", line 414, in __init__
  File "dropbox/sync_engine/nucleus/classic_client/thin_adapter/in_proc.pyc", line 217, in __init__
  File "dropbox/sync_engine/nucleus/classic_client/thin_adapter/in_proc.pyc", line 628, in _init_new_engine_locked
  File "dropbox/sync_engine/nucleus/thin_client/client.pyc", line 143, in __init__
  File "nucleus_python.pyx", line 87, in nucleus_python.NucleusSyncEngine.__cinit__
nucleus_python.SyncEngineError: Initializing engine |>> Initializing platform |>> Checking if filesystem is supported |>> Filesystem is not supported: "FUSE"


This seems to be a pretty common problem to which Dropbox has not given a specific ans

https://www.google.com/search?q=Storing+your+home+folder+on+a+network+share+can+also+cause+an+error.&oq=Storing+your+home+folder+on+a+network+share+can+also+cause+an+error.&aqs=chrome..69i57j0.467j0j4&sourceid=chrome&ie=UTF-8

Also my home folder  is not on a network share

**Comment by otherguy** [comment]
So, I have identified this issue. The filesystem fix is unable to work around the filsystem detection in the new Dropbox client.

For now, mounting a volume will not work. I'm looking into a new workaround.

**Comment by otherguy** [comment]
Closing this issue in favor of #6.
