### ISSUE TITLE
[FEATURE] Add ability to skip permission checks

### ISSUE THREAD

**Issue by edyounis** [otherguy/docker-dropbox#25]
**Is your feature request related to a problem? Please describe.**
`chown -R` command can create long boot times (>1 day) with flattened encrypted directories, like [cryfs](github.com/cryfs/cryfs)

**Describe the solution you'd like**
1. Add environment variable `DROPBOX_SKIP_PERMISSIONS`
2. In the entrypoint script change:
```sh
# Change ownership to dropbox account on all working folders.
chown -R ${DROPBOX_UID}:${DROPBOX_GID} /opt/dropbox
```

to

```sh
# Change ownership to dropbox account on all working folders.
if [[ -z "$DROPBOX_SKIP_PERMISSIONS" ]]; then
    chown -R ${DROPBOX_UID}:${DROPBOX_GID} /opt/dropbox
else
    echo "Skipping permissions check, ensure the dropbox user owns all files."
fi
```

**Additional context**
N/A

**Comment by otherguy** [comment]
Hey @edyounis and thanks for your feature request! Sorry I'm only getting around to this now. 

Version [1.8.5](https://github.com/otherguy/docker-dropbox/releases/tag/1.8.5) now has a flag to do just that!

```bash
docker run --rm -it -e SKIP_SET_PERMISSIONS=true otherguy/dropbox:latest
```

I would be grateful if you could try it out and let me know if this works for you!
