### ISSUE TITLE
very slow upload/download speeds using Synology QNAP Docker instance

### ISSUE THREAD

**Issue by nickdiacre** [otherguy/docker-dropbox#28]
**Describe the bug**
Up and down speeds are from 0-100KBps

**Versions:**
 - Docker: 20.10.3
 - Docker Compose (_if used_) (`docker-compose --version`):  1.27.4, build 40524192
 - Image Name:  otherguy/dropbox:latest
 - Image ID: 8654ae888671

I have this up and running but the download speeds are very slow. Is there anyway I can carry out a speed test within the container. Network runs at 500meg down, 250meg up.

Qnap TS-H1283XU-RP NAS.

![image](https://user-images.githubusercontent.com/5656214/122572876-14315e80-d046-11eb-827b-dae630e9a2c8.png)

**Comment by otherguy** [comment]
Thanks for the report!

Could you please run the normal Dropbox client and compare speeds? In my experience these up- and download speeds are pretty normal.

Please also try using the `throttle` command of Dropbox:

```bash
$ dropbox throttle
set bandwidth limits for Dropbox
dropbox throttle DOWNLOAD UPLOAD

Set bandwidth limits for file sync.

DOWNLOAD - either "unlimited" or a manual limit in KB/s
UPLOAD - one of "unlimited", "auto", or a manual limit in KB/s
```

Inside the container you would run it like this:
```bash
$ docker exec [dropbox-container-name] gosu dropbox dropbox throttle unlimited unlimited
set
```

Additionally, how exactly did you start the container (full command)? Are you using `--network=host`? If not, this could give you some additional speed.

**Comment by nickdiacre** [comment]
the container is started using --network=host, it is started using container station but it was initially run from the cli using the --network=host option [otherwise it was as per your readme.md.

I can't really see what the current sync speed is on my windows machine, the new version of the app doesn't appear to show it

**Comment by otherguy** [comment]
Thank you for the reply!

I’m not a Windows user so I won’t be of much help, but there are [various tools that can show the bandwidth used by an app](https://www.hongkiat.com/blog/monitor-internet-usage/)! 

Did you try the `throttle` command?

**Comment by otherguy** [comment]
@nickdiacre did you get around to trying my suggestions?

**Comment by nickdiacre** [comment]
huh, I am a bit confused now, as I am getting 2meg speeds, which is much better, but its been stuck on the same file numbers for days:

```Uploading 2,920,232 files...
Downloading 2,943,884 files...
Syncing 5,974,357 files • 3 hrs```

Wondering how/why it's stuck and maybe thats why the speeds were slow.

**Comment by otherguy** [comment]
That is entirely possible. I have the same issue when I'm syncing lots of small files.

Unfortunately, that is not something I can change with this Docker image -- it's still only using the official Linux Dropbox client. Your best bet is contacting Dropbox support and asking them, or [asking in the Dropbox community forums](https://www.dropboxforum.com/t5/Help-from-the-Community/ct-p/101001000).
