### ISSUE TITLE
[FEATURE] Run sysctl command in Docker image

### ISSUE THREAD

**Issue by DiegoQueiroz** [otherguy/docker-dropbox#29]
When configuring Dropbox, I'm used in seeing this message:

> Syncing 118,484 files • 25 mins
> Downloading 118,484 files (0.0 KB/sec, 25 mins)
> Unable to monitor entire Dropbox folder hierarchy. Please run "echo fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf; sudo sysctl -p" and restart Dropbox to fix the problem.
> Syncing 117,824 files • 14 mins
> Downloading 117,824 files (0.0 KB/sec, 14 mins)
> Syncing 116,862 files • 11 mins

I think it would be great if you already run this command in the image.

**Comment by otherguy** [comment]
Hi @DiegoQueiroz and thanks for your suggestion. I took the liberty of turning this bug report into a feature request.

Unfortunately, this cannot be done. The command *needs* to be run on the *host system*, and *not* inside the Docker container!

Where are you running this? In case it's on a Synology system, I wrote a [description of how to permanently solve this](https://github.com/otherguy/docker-dropbox/issues/16#issuecomment-759378965).

On Linux you can do something similar.

**Comment by DiegoQueiroz** [comment]
I wasn't aware this config should be done in the host machine. Sorry.

It would be great if you add to the documentation this statement as a FAQ or something.

**Comment by otherguy** [comment]
No problem Diego! 🙂
This is actually already in the README: https://github.com/otherguy/docker-dropbox#monitoring-more-than-10000-folders-on-linux

**Comment by DiegoQueiroz** [comment]
So everything is addressed. :-)

When I read Docker Hub text I thought they were the same text and didn't read the README in the repository, my fault (I came to GitHub just to report the issue, and read nothing). If it is not much to ask, update Docker Hub with this info too.

**Comment by otherguy** [comment]
Oops that should have happened automatically! Thanks for letting me know!

Just updated the README on Docker Hub manually.
