### ISSUE TITLE
Errors dropbox-filesystem-fix

### ISSUE THREAD

**Issue by KlausGlueckert** [otherguy/docker-dropbox#4]
The image didnt build because it says a library was missing:

`ImportError: libglapi.so.0: cannot open shared object file: No such file or directory`

I added in the Dockerfile:

` && apt-get install -y --no-install-recommends apt-transport-https libc6 libglapi-mesa libxdamage1 libxfixes3 libxcb-glx0 libxcb-dri2-0 libxcb-dri3-0 libxcb-present0 libxcb-sync1 libxshmfence1 libxxf86vm1`

After that it builds, but doesnt work:
```

Checking for latest Dropbox version...
Latest   : 94.4.384
Installed: 94.4.384
Dropbox is up-to-date

Patching dropbox_start.py for updated dropboxd path
sed: can't read /opt/dropbox-filesystem-fix/dropbox_start.py: No such file or directory
sed: can't read /opt/dropbox-filesystem-fix/dropbox_start.py: No such file or directory
```

**Comment by KlausGlueckert** [comment]
See also: https://www.dropboxforum.com/t5/Dropbox-installs-integrations/Headless-install-on-Debian-libglapi-so-0-cannot-open-shared/td-p/396457

I think the problems re-occur, because you are not referencing a fixed version of debian, and of course that the dropbox binary updates. Maybe a better way is to put the binary in the Repo. Then everything stays consistent and it should update itsself at first launch

**Comment by dwhite44** [comment]
Same error for me. Here's the full log:

DROPBOX_UID not specified, defaulting to dropbox user id (1000)
DROPBOX_GID not specified, defaulting to dropbox user group id (1000)
Checking for latest Dropbox version...
Latest   : 94.4.384
Installed: 94.4.384
Dropbox is up-to-date
Patching dropbox_start.py for updated dropboxd path
Starting dropboxd (94.4.384)...
dropbox: locating interpreter
!! dropbox: failed to create log file (Permission denied)!
dropbox: initializing
dropbox: initializing python 3.7.5
dropbox: setting program path '/opt/dropbox/bin/dropbox-lnx.x86_64-94.4.384/dropbox'
dropbox: setting python path '/opt/dropbox/bin/dropbox-lnx.x86_64-94.4.384:/opt/dropbox/bin/dropbox-lnx.x86_64-94.4.384/python-packages.zip'
dropbox: python initialized
dropbox: running dropbox
dropbox: setting args
dropbox: applying overrides
dropbox: running main script
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-94.4.384/cryptography.hazmat.bindings._constant_time.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-94.4.384/cryptography.hazmat.bindings._openssl.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-94.4.384/cryptography.hazmat.bindings._padding.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-94.4.384/psutil._psutil_linux.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-94.4.384/psutil._psutil_posix.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-94.4.384/apex._apex.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-94.4.384/tornado.speedups.cpython-37m-x86_64-linux-gnu.so'
dropbox: load fq extension '/opt/dropbox/bin/dropbox-lnx.x86_64-94.4.384/PyQt5.QtWidgets.cpython-37m-x86_64-linux-gnu.so'
Traceback (most recent call last):
  File "dropbox/client/main.pyc", line 262, in <module>
  File "dropbox/foundation/navigation_service/factory.pyc", line 19, in <module>
  File "dropbox/foundation/navigation_service/navigation_service_impl.pyc", line 57, in <module>
  File "dropbox/foundation/html_views/electron/manager_factory.pyc", line 13, in <module>
  File "dropbox/foundation/html_views/local/common/manager.pyc", line 33, in <module>
  File "dropbox/client/features/model_registry.pyc", line 13, in <module>
  File "dropbox/client/features/generated_models.pyc", line 279, in <module>
  File "dropbox/client/features/previews/view_anchor.pyc", line 104, in <module>
  File "<_bootstrap_overrides>", line 153, in load_module
ImportError: libglapi.so.0: cannot open shared object file: No such file or directory
!! dropbox: fatal python exception:
['Traceback (most recent call last):\n', '  File "dropbox/client/main.pyc", line 262, in <module>\n', '  File "dropbox/foundation/navigation_service/factory.pyc", line 19, in <module>\n', '  File "dropbox/foundation/navigation_service/navigation_service_impl.pyc", line 57, in <module>\n', '  File "dropbox/foundation/html_views/electron/manager_factory.pyc", line 13, in <module>\n', '  File "dropbox/foundation/html_views/local/common/manager.pyc", line 33, in <module>\n', '  File "dropbox/client/features/model_registry.pyc", line 13, in <module>\n', '  File "dropbox/client/features/generated_models.pyc", line 279, in <module>\n', '  File "dropbox/client/features/previews/view_anchor.pyc", line 104, in <module>\n', '  File "<_bootstrap_overrides>", line 153, in load_module\n', 'ImportError: libglapi.so.0: cannot open shared object file: No such file or directory\n'] (error 3)

**Comment by KlausGlueckert** [comment]
@otherguy do you have possible solution? I am kind of screwed atm :(

**Comment by otherguy** [comment]
I saw this error as well now, my container crashed too. Will look into it in the next few days.

**Comment by KlausGlueckert** [comment]
thanks @otherguy

**Comment by asmaloney** [comment]
Just ran into this as well... Same log as @dwhite44.

**Comment by asmaloney** [comment]
To followup after more looking around, @adamkdean has a fix [here](https://github.com/adamkdean/docker-dropbox/commit/149f8ec9cc0e1a5f0d7fb77f96503e75a5cb27ec).

As he pointed out in the [original repo](https://github.com/janeczku/docker-dropbox/issues/40):

> This could perhaps be tidier but I don't have time right now to work out which of those deps are strictly needed/not needed for dropbox.

**Comment by otherguy** [comment]
Thanks @asmaloney and @KlausGlueckert 

I have fixed the build issues. Can you please test and verify if it's working for you?

Please also let me know what configuration you're using this in (operating system, startup parameters).

**Note**: For now, mounting /opt/dropbox/Dropbox to a Docker volume *will not work*! See #3.
